apiVersion: apps/v1
kind: ReplicaSet #Pod, Deployment, ReplicationController, Service, ReplicaSet, DaemonSet, Job
metadata:
  name: first-replicaset
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      car: ford
  template: 
    metadata:
      labels:
        car: ford
    spec:
      containers:
      - name: cont1
        image: nginx
