apiVersion: v1
kind: Service #Pod, Deployment, ReplicationController, Service, ReplicaSet, DaemonSet, Job
metadata:
  name: cluster-service
spec: 
  selector:
    app: nginx-app1
  type: ClusterIP # optional, by default it takes it as ClusterIP
  ports:
    - protocol: TCP
      port: 3000 # service port for external apps
      targetPort: 80 # service to pod
